version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5600:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=cinema
      - POSTGRES_USER=cinema
      - POSTGRES_DB=cinema
